Repository mysterious-shailendr/powercred-slack-bot, pull requests merged in 2023-10, with the labels that each got.

#1 Init
  .gitignore
  README.md
  env.txt
  requirements.txt
  run.bat
  run.sh
  src/Interface/appscript.js
  src/Interface/calendar.block.json
  src/__pycache__/handler.cpython-311.pyc
  src/__pycache__/main.cpython-311.pyc
  src/apps/LeaveTracker/__pycache__/leave_tracker.cpython-311.pyc
  src/apps/LeaveTracker/__pycache__/leave_tracker_router.cpython-311.pyc
  src/apps/LeaveTracker/__pycache__/router.cpython-311.pyc
  src/apps/LeaveTracker/leave_tracker.py
  src/apps/LeaveTracker/models/leaves.model.py
  src/apps/LeaveTracker/router.py
  src/apps/__init__.py
  src/apps/__pycache__/__init__.cpython-311.pyc
  src/apps/onboard/onboard.py
  src/core/Llama2.py
  src/core/__init__.py
  src/core/__pycache__/Llama2.cpython-311.pyc
  src/core/__pycache__/__init__.cpython-311.pyc
  src/core/__pycache__/handler.cpython-311.pyc
  src/core/__pycache__/manager.cpython-311.pyc
  src/core/__pycache__/paLM2.cpython-311.pyc
  src/core/handler.py
  src/core/manager.py
  src/core/paLM2.py
  src/core/spreadsheet.py
  src/data/main.py
  src/data/powercred.json
  src/main.py
Labels: enhancement

#2 slackeventsapi requirement added
  requirements.txt
Labels: bug

#3 spacy requirments added
  requirements.txt
Labels: bug

#4 slack requirements added
  requirements.txt
Labels: bug

#5 update gitignore file
  .gitignore
Labels: documentation, hacktoberfest-accepted

#6 Dynamic Spreadsheet URL
  src/apps/LeaveTracker/leave_tracker.py
  src/core/handler.py
  src/core/manager.py
  src/script/appscript.js
Labels: bug, hacktoberfest-accepted

#7 mermaid flow diagram
  README.md
Labels: documentation, hacktoberfest-accepted
